# Generated by Django 2.2.5 on 2020-04-16 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControlPloicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_title', models.CharField(max_length=120)),
                ('policy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('id', 'ID'), ('bachelor', 'Bachelor'), ('driving_licence', 'Driving Licence'), ('bank_account_passbook', 'Bank Account Passbook'), ('telephone_bill', 'Telephone Bill'), ('electricity_bill', 'Electricity Bill')], max_length=120)),
                ('document', models.FileField(upload_to=documents.utils.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
